// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradeNetProject.Data;

#nullable disable

namespace TradenetProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TradeNetProject.Models.ComplianceRecord", b =>
                {
                    b.Property<int>("ComplianceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ComplianceID"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ComplianceID");

                    b.ToTable("ComplianceRecords");

                    b.HasData(
                        new
                        {
                            ComplianceID = 1,
                            BusinessName = "ABC Traders",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2026-01-05",
                            InspectionType = "Annual Audit",
                            Remarks = "All documents in order, no violations found.",
                            Result = "Passed"
                        },
                        new
                        {
                            ComplianceID = 2,
                            BusinessName = "XYZ Exports",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2026-01-10",
                            InspectionType = "Safety Inspection",
                            Remarks = "Minor safety signage missing, corrective notice issued.",
                            Result = "Failed"
                        },
                        new
                        {
                            ComplianceID = 3,
                            BusinessName = "Global Imports Ltd",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2026-01-12",
                            InspectionType = "License Compliance",
                            Remarks = "Operating license valid, import permits verified.",
                            Result = "Passed"
                        },
                        new
                        {
                            ComplianceID = 4,
                            BusinessName = "Eastern Commerce",
                            InspectedBy = "",
                            InspectedDate = "2026-01-18",
                            InspectionType = "Tax Compliance",
                            Remarks = "",
                            Result = "Pending"
                        },
                        new
                        {
                            ComplianceID = 5,
                            BusinessName = "Pacific Wholesale",
                            InspectedBy = "",
                            InspectedDate = "2026-01-20",
                            InspectionType = "Environmental Check",
                            Remarks = "",
                            Result = "Pending"
                        },
                        new
                        {
                            ComplianceID = 6,
                            BusinessName = "Sunrise Trading Co",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2025-12-28",
                            InspectionType = "Annual Audit",
                            Remarks = "Expired trade certificate, renewal required.",
                            Result = "Failed"
                        },
                        new
                        {
                            ComplianceID = 7,
                            BusinessName = "Delta Freight",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2026-02-01",
                            InspectionType = "Safety Inspection",
                            Remarks = "Fire extinguishers up to date, exits clearly marked.",
                            Result = "Passed"
                        },
                        new
                        {
                            ComplianceID = 8,
                            BusinessName = "Coastal Ventures",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2026-02-05",
                            InspectionType = "License Compliance",
                            Remarks = "Export license expired, renewal in progress.",
                            Result = "Failed"
                        },
                        new
                        {
                            ComplianceID = 9,
                            BusinessName = "Metro Distributors",
                            InspectedBy = "",
                            InspectedDate = "2026-02-08",
                            InspectionType = "Tax Compliance",
                            Remarks = "",
                            Result = "Pending"
                        },
                        new
                        {
                            ComplianceID = 10,
                            BusinessName = "Summit Logistics",
                            InspectedBy = "Trade Officer",
                            InspectedDate = "2026-02-10",
                            InspectionType = "Annual Audit",
                            Remarks = "All regulatory filings current, warehouse standards met.",
                            Result = "Passed"
                        });
                });

            modelBuilder.Entity("TradeNetProject.Models.Document", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubmittedDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentID");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentID = 1,
                            BusinessName = "ABC Traders",
                            DocumentType = "Trade Certificate",
                            Status = "Pending",
                            SubmittedDate = "2026-01-10",
                            VerifiedBy = ""
                        },
                        new
                        {
                            DocumentID = 2,
                            BusinessName = "XYZ Exports",
                            DocumentType = "Tax Clearance",
                            Status = "Pending",
                            SubmittedDate = "2026-01-12",
                            VerifiedBy = ""
                        },
                        new
                        {
                            DocumentID = 3,
                            BusinessName = "Global Imports Ltd",
                            DocumentType = "Import Permit",
                            Status = "Verified",
                            SubmittedDate = "2026-01-08",
                            VerifiedBy = "Trade Officer"
                        },
                        new
                        {
                            DocumentID = 4,
                            BusinessName = "Eastern Commerce",
                            DocumentType = "Business Registration",
                            Status = "Pending",
                            SubmittedDate = "2026-01-15",
                            VerifiedBy = ""
                        },
                        new
                        {
                            DocumentID = 5,
                            BusinessName = "Pacific Wholesale",
                            DocumentType = "Export License",
                            Status = "Rejected",
                            SubmittedDate = "2026-01-05",
                            VerifiedBy = "Trade Officer"
                        },
                        new
                        {
                            DocumentID = 6,
                            BusinessName = "Sunrise Trading Co",
                            DocumentType = "Trade Certificate",
                            Status = "Verified",
                            SubmittedDate = "2026-01-18",
                            VerifiedBy = "Trade Officer"
                        },
                        new
                        {
                            DocumentID = 7,
                            BusinessName = "Delta Freight",
                            DocumentType = "Tax Clearance",
                            Status = "Pending",
                            SubmittedDate = "2026-01-20",
                            VerifiedBy = ""
                        },
                        new
                        {
                            DocumentID = 8,
                            BusinessName = "Coastal Ventures",
                            DocumentType = "Import Permit",
                            Status = "Verified",
                            SubmittedDate = "2026-01-22",
                            VerifiedBy = "Trade Officer"
                        },
                        new
                        {
                            DocumentID = 9,
                            BusinessName = "Metro Distributors",
                            DocumentType = "Business Registration",
                            Status = "Rejected",
                            SubmittedDate = "2026-01-25",
                            VerifiedBy = "Trade Officer"
                        },
                        new
                        {
                            DocumentID = 10,
                            BusinessName = "Summit Logistics",
                            DocumentType = "Export License",
                            Status = "Pending",
                            SubmittedDate = "2026-01-28",
                            VerifiedBy = ""
                        });
                });

            modelBuilder.Entity("TradeNetProject.Models.MarketRecord", b =>
                {
                    b.Property<int>("RecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordID"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Revenue")
                        .HasColumnType("float");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalVendors")
                        .HasColumnType("int");

                    b.HasKey("RecordID");

                    b.ToTable("MarketRecords");

                    b.HasData(
                        new
                        {
                            RecordID = 1,
                            Category = "Wholesale",
                            Location = "Downtown District",
                            MarketName = "Central Trade Market",
                            Revenue = 450000.0,
                            Status = "Active",
                            TotalVendors = 124
                        },
                        new
                        {
                            RecordID = 2,
                            Category = "Export",
                            Location = "Harbor Zone",
                            MarketName = "Eastern Export Hub",
                            Revenue = 320000.0,
                            Status = "Active",
                            TotalVendors = 86
                        },
                        new
                        {
                            RecordID = 3,
                            Category = "Retail",
                            Location = "South Bank",
                            MarketName = "Riverside Market",
                            Revenue = 125000.0,
                            Status = "Under Review",
                            TotalVendors = 45
                        },
                        new
                        {
                            RecordID = 4,
                            Category = "Import",
                            Location = "Industrial Park",
                            MarketName = "North Import Center",
                            Revenue = 275000.0,
                            Status = "Active",
                            TotalVendors = 67
                        },
                        new
                        {
                            RecordID = 5,
                            Category = "Retail",
                            Location = "West End",
                            MarketName = "Sunset Bazaar",
                            Revenue = 85000.0,
                            Status = "Inactive",
                            TotalVendors = 32
                        },
                        new
                        {
                            RecordID = 6,
                            Category = "Wholesale",
                            Location = "Uptown Heights",
                            MarketName = "Hilltop Trade Plaza",
                            Revenue = 390000.0,
                            Status = "Active",
                            TotalVendors = 98
                        },
                        new
                        {
                            RecordID = 7,
                            Category = "Import",
                            Location = "Lake District",
                            MarketName = "Lakeside Commerce Park",
                            Revenue = 210000.0,
                            Status = "Active",
                            TotalVendors = 53
                        },
                        new
                        {
                            RecordID = 8,
                            Category = "Retail",
                            Location = "Heritage Quarter",
                            MarketName = "Old Town Market",
                            Revenue = 72000.0,
                            Status = "Under Review",
                            TotalVendors = 28
                        },
                        new
                        {
                            RecordID = 9,
                            Category = "Export",
                            Location = "Airport Road",
                            MarketName = "Greenfield Export Zone",
                            Revenue = 415000.0,
                            Status = "Active",
                            TotalVendors = 74
                        },
                        new
                        {
                            RecordID = 10,
                            Category = "Wholesale",
                            Location = "Coastal Strip",
                            MarketName = "Bayview Trading Center",
                            Revenue = 165000.0,
                            Status = "Inactive",
                            TotalVendors = 41
                        });
                });

            modelBuilder.Entity("TradeNetProject.Models.TradeLicense", b =>
                {
                    b.Property<int>("LicenseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseID"));

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LicenseID");

                    b.ToTable("TradeLicenses");

                    b.HasData(
                        new
                        {
                            LicenseID = 1,
                            BusinessName = "ABC Traders",
                            Status = "Pending",
                            Type = "Import"
                        },
                        new
                        {
                            LicenseID = 2,
                            BusinessName = "XYZ Exports",
                            Status = "Pending",
                            Type = "Export"
                        },
                        new
                        {
                            LicenseID = 3,
                            BusinessName = "Global Imports Ltd",
                            Status = "Approved",
                            Type = "Import"
                        },
                        new
                        {
                            LicenseID = 4,
                            BusinessName = "Eastern Commerce",
                            Status = "Approved",
                            Type = "Export"
                        },
                        new
                        {
                            LicenseID = 5,
                            BusinessName = "Pacific Wholesale",
                            Status = "Rejected",
                            Type = "Import"
                        },
                        new
                        {
                            LicenseID = 6,
                            BusinessName = "Sunrise Trading Co",
                            Status = "Approved",
                            Type = "Export"
                        },
                        new
                        {
                            LicenseID = 7,
                            BusinessName = "Delta Freight",
                            Status = "Pending",
                            Type = "Import"
                        },
                        new
                        {
                            LicenseID = 8,
                            BusinessName = "Coastal Ventures",
                            Status = "Approved",
                            Type = "Export"
                        },
                        new
                        {
                            LicenseID = 9,
                            BusinessName = "Metro Distributors",
                            Status = "Pending",
                            Type = "Import"
                        },
                        new
                        {
                            LicenseID = 10,
                            BusinessName = "Summit Logistics",
                            Status = "Rejected",
                            Type = "Export"
                        });
                });

            modelBuilder.Entity("TradeNetProject.Models.TradeOfficer", b =>
                {
                    b.Property<int>("OfficerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfficerID"));

                    b.Property<DateTime>("DateOfJoining")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfficerID");

                    b.ToTable("TradeOfficers");

                    b.HasData(
                        new
                        {
                            OfficerID = 1001,
                            DateOfJoining = new DateTime(2021, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "Trade Licensing & Compliance",
                            Designation = "Senior Trade Officer",
                            Email = "officer@tradenet.gov",
                            EmployeeCode = "TO-2024-1001",
                            FullName = "Trade Officer",
                            Phone = "+1 (800) 555-0142",
                            Region = "North America – Eastern Division",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("TradeNetProject.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionID"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = 1,
                            Amount = 5000.0,
                            BusinessName = "ABC Traders",
                            Status = "Completed",
                            Type = "Sale"
                        },
                        new
                        {
                            TransactionID = 2,
                            Amount = 8000.0,
                            BusinessName = "XYZ Exports",
                            Status = "Pending",
                            Type = "Purchase"
                        },
                        new
                        {
                            TransactionID = 3,
                            Amount = 12500.0,
                            BusinessName = "Global Imports Ltd",
                            Status = "Completed",
                            Type = "Sale"
                        },
                        new
                        {
                            TransactionID = 4,
                            Amount = 3200.0,
                            BusinessName = "Eastern Commerce",
                            Status = "Completed",
                            Type = "Purchase"
                        },
                        new
                        {
                            TransactionID = 5,
                            Amount = 9750.0,
                            BusinessName = "Pacific Wholesale",
                            Status = "Pending",
                            Type = "Sale"
                        },
                        new
                        {
                            TransactionID = 6,
                            Amount = 15000.0,
                            BusinessName = "Sunrise Trading Co",
                            Status = "Completed",
                            Type = "Purchase"
                        },
                        new
                        {
                            TransactionID = 7,
                            Amount = 6800.0,
                            BusinessName = "Delta Freight",
                            Status = "Pending",
                            Type = "Sale"
                        },
                        new
                        {
                            TransactionID = 8,
                            Amount = 22000.0,
                            BusinessName = "Coastal Ventures",
                            Status = "Completed",
                            Type = "Purchase"
                        },
                        new
                        {
                            TransactionID = 9,
                            Amount = 4100.0,
                            BusinessName = "Metro Distributors",
                            Status = "Completed",
                            Type = "Sale"
                        },
                        new
                        {
                            TransactionID = 10,
                            Amount = 18500.0,
                            BusinessName = "Summit Logistics",
                            Status = "Pending",
                            Type = "Purchase"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
